/lib
/usr/lib
/android/system_ext/lib
/android/system_ext/lib64
/android/system/lib
/android/system/lib64
/android/system/lib/hw
/android/system/lib/hw/extractors
/android/system/lib/bootstrap
/android/system/lib64
/android/system/lib64/hw
/android/system/lib64/extractors
/android/system/lib64/bootstrap
/android/system/lib64/extractors
/android/vendor/lib
/android/vendor/lib/egl
/android/vendor/lib/hw
/android/vendor/lib/mediacas
/android/vendor/lib/mediadrm
/android/vendor/lib/modules
/android/vendor/lib/mnpidevice
/android/vendor/lib/soundfx
/android/vendor/lib64
/android/vendor/lib64/egl
/android/vendor/lib64/hw
/android/vendor/lib64/mediacas
/android/vendor/lib64/mediadrm
/android/vendor/lib64/mnpidevice
/android/vendor/lib64/soundfx