import re
import os


def extract_config_flags_from_commented(file_path):
    """
    Extract CONFIG flag names from lines like "# CONFIG_XXXXX is not set"
    """
    config_flags = set()
    try:
        with open(file_path, 'r') as file:
            for line in file:
                line = line.strip()
                # Match pattern: # CONFIG_XXXXX is not set
                match = re.match(r'^# (CONFIG_\w+) is not set$', line)
                if match:
                    config_flags.add(match.group(1))
        print(f"Found {len(config_flags)} commented 'not set' flags")
        return config_flags
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        return set()
    except Exception as e:
        print(f"Error reading file '{file_path}': {e}")
        return set()


def extract_enabled_flags_from_kernel_config(file_path):
    """
    Extract CONFIG flag names that are set to 'y' from kernel config
    """
    enabled_flags = set()
    try:
        with open(file_path, 'r') as file:
            for line in file:
                line = line.strip()
                # Match pattern: CONFIG_XXXXX=y
                match = re.match(r'^(CONFIG_\w+)=y$', line)
                if match:
                    enabled_flags.add(match.group(1))
        print(f"Found {len(enabled_flags)} flags enabled with 'y'")
        return enabled_flags
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        return set()
    except Exception as e:
        print(f"Error reading file '{file_path}': {e}")
        return set()


def find_conflicting_flags(commented_flags, enabled_flags):
    """
    Find flags that are marked as 'not set' but are actually enabled
    """
    conflicts = commented_flags.intersection(enabled_flags)
    return conflicts


def main(commented_file_path, kernel_config_file_path, output_file_path):
    """
    Main function that accepts file paths as parameters

    Args:
        commented_file_path: Path to the commented_not_set_flags.txt file
        kernel_config_file_path: Path to the kernel config file (e.g., 4.14.193-kernel_configs.txt)
        output_file_path: Path for the output file where results will be saved
    """
    print("CONFIG Flag Conflict Checker")
    print("=" * 40)

    # Validate input files exist
    if not os.path.exists(commented_file_path):
        print(f"Error: File '{commented_file_path}' does not exist.")
        return

    if not os.path.exists(kernel_config_file_path):
        print(f"Error: File '{kernel_config_file_path}' does not exist.")
        return

    print("\nProcessing files...")
    print("-" * 30)

    # Extract flags from both files
    commented_flags = extract_config_flags_from_commented(commented_file_path)
    enabled_flags = extract_enabled_flags_from_kernel_config(kernel_config_file_path)

    if not commented_flags or not enabled_flags:
        print("Error: Could not extract flags from one or both files.")
        return

    # Find conflicts
    conflicting_flags = find_conflicting_flags(commented_flags, enabled_flags)

    print(f"\nAnalysis Results:")
    print(f"- Total commented 'not set' flags: {len(commented_flags)}")
    print(f"- Total enabled flags (=y): {len(enabled_flags)}")
    print(f"- Conflicting flags (marked 'not set' but enabled): {len(conflicting_flags)}")

    # Write results to output file
    try:
        with open(output_file_path, 'w') as file:
            file.write("CONFIG FLAGS MARKED AS 'NOT SET' BUT ACTUALLY ENABLED\n")
            file.write("=" * 55 + "\n")
            file.write(f"Total conflicts found: {len(conflicting_flags)}\n")
            file.write("Generated by: CONFIG Flag Conflict Checker\n")
            file.write("-" * 55 + "\n\n")

            if conflicting_flags:
                # Sort flags alphabetically for better readability
                sorted_conflicts = sorted(conflicting_flags)
                for i, flag in enumerate(sorted_conflicts, 1):
                    file.write(f"{i:3d}. {flag}\n")
            else:
                file.write("No conflicting flags found!\n")
                file.write("All commented 'not set' flags are indeed not enabled in the kernel config.\n")

        print(f"\nResults exported to: {output_file_path}")

        if conflicting_flags:
            print(f"\n⚠️  WARNING: Found {len(conflicting_flags)} conflicting flags!")
            print("These flags are commented as 'not set' but are actually enabled in your kernel config.")
            print("\nFirst 10 conflicts:")
            sorted_conflicts = sorted(conflicting_flags)
            for i, flag in enumerate(sorted_conflicts[:10], 1):
                print(f"  {i}. {flag}")
            if len(conflicting_flags) > 10:
                print(f"  ... and {len(conflicting_flags) - 10} more (see output file for complete list)")
        else:
            print("\n✅ No conflicts found! Your configuration appears consistent.")

    except Exception as e:
        print(f"Error writing to output file '{output_file_path}': {e}")
        return


if __name__ == "__main__":
    # Example usage - replace these paths with your actual file paths
    commented_file = "C:\\Users\\PC\\Desktop\\Email\\- LLM\RP3+\\Linux\\commented_not_set_flags.txt"
    kernel_config_file = "C:\\Users\\PC\\Desktop\\Email\\- LLM\\RP3+\\Linux\\4.14.193 kernel_configs.txt"
    output_file = "C:\\Users\\PC\\Desktop\\Email\\- LLM\\RP3+\\Linux\\Unmatched_configs"

    # Call the main function with your file paths
    main(commented_file, kernel_config_file, output_file)
