#=========================================================
#  Target         Format        Source        Type     Tag
#=========================================================
$sda:0xf00000-0x1700000 zero - - #nr_fixnv2
$sda:0x2100000-0x2b00000 zero - - #nr_runtimenv1
$sda:0x2b00000-0x3500000 zero - - #nr_runtimenv2
$sda:0x3500000-0x5d00000 bin images/recovery.img img #recovery
$sda:0x6300000-0x6900000 zero - - #trustos_bak
$sda:0x6a00000-0x6b00000 zero - - #sml_bak
$sda:0x6b00000-0x6d00000 bin images/u-boot-sign.bin img #uboot
$sda:0x6d00000-0x6f00000 zero - - #uboot_bak
$sda:0x6f00000-0x7300000 zero - - #uboot_log
$sda:0x7300000-0x7a00000 bin images/3.5_v0_BMP.bmp img #logo
$sda:0x7a00000-0x8100000 bin images/jingboot_v1_BMP.bmp img #fbootlogo
$sda:0x8100000-0x8200000 bin images/sharkl5pro_cm4.bin img #l_pmsys
$sda:0x8200000-0x8800000 bin images/sharkl5pro_pubcp_AGCP_DSP.bin img #l_agdsp
$sda:0x8800000-0x8900000 bin images/gnssmodem.bin img #gnssmodem
$sda:0x8900000-0x9300000 bin images/EXEC_KERNEL_IMAGE.bin img #wcnmodem
$sda:0x9300000-0x9500000 bin images/persist.img img #persist
$sda:0x9500000-0x9600000 bin images/u-boot-spl-16k-sign.bin(1) img #nr_spl
$sda:0x9600000-0x9700000 bin images/sml-sign.bin(1) img #nr_sml
$sda:0x9700000-0x9900000 bin images/u-boot-sign.bin(1) img #nr_uboot
$sda:0x9900000-0xbc00000 bin images/boot.img(1) img #nr_boot
$sda:0xbc00000-0xbd00000 bin images/sharkl5pro_cm4.bin img #nr_pmsys
$sda:0xbd00000-0xc300000 bin images/sharkl5pro_pubcp_AGCP_DSP.bin img #nr_agdsp
$sda:0xc300000-0xeb00000 bin images/SC9600_sharkl5pro_pubcp_modem.dat img #nr_modem
$sda:0xeb00000-0xf300000 bin images/sharkl5pro_pubcp_customer_nvitem.bin img #nr_v3phy
$sda:0xf300000-0xfb00000 bin images/sharkl5pro_pubcp_customer_nvitem.bin img #nr_nrphy
$sda:0xfb00000-0x10000000 bin images/Orca_NR_phy_NR_XC0_DSP.bin img #nr_nrdsp1
$sda:0x10000000-0x10500000 zero - - #nr_nrdsp2
$sda:0x10500000-0x10700000 bin images/sharkl5pro_pubcp_customer_nvitem.bin img #nr_deltanv
$sda:0x10800000-0x10900000 zero - - #teecfg_bak
$sda:0x10900000-0x12c00000 bin images/boot.img img #boot
$sda:0x12c00000-0x13400000 bin images/dtbo.img img #dtbo
$sda:0x13400000-0xaf800000 bin images/system.img img #system
$sda:0xaf800000-0xf0600000 bin images/vendor.img img #vendor
$sda:0xf0600000-0xf9c00000 bin images/cache.img img #cache
$sda:0xf9c00000-0xfe700000 bin images/socko.img img #socko
$sda:0xfe700000-0x100000000 bin images/odmko.img img #odmko
$sda:0x100000000-0x100100000 bin images/vbmeta-sign.img img #vbmeta
$sda:0x100100000-0x100200000 zero - - #vbmeta_bak
$sda:0x100200000-0x101200000 zero - - #metadata
$sda:0x101200000-0x101c00000 zero - - #sysdumpdb
$sda:0x101c00000-0x101d00000 bin images/vbmeta_system.img img #vbmeta_system
$sda:0x101d00000-0x101e00000 bin images/vbmeta_vendor.img img #vbmeta_vendor
$sda:0x101e00000-0xb01e00000 bin images/rootfs.img img #rootfs
$sda:0xd81600000-0xd81e00000 bin images/lowbattery_v0_BMP.bmp img #lowbattery
$sda:0xd81e00000-~0x21000 f2fs - - yes #userdata
$sda gpt images/part_table_backup.bin gen #partition table backup
